# Generated by Django 2.1.7 on 2019-03-21 15:50

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('bettor', models.CharField(max_length=11)),
                ('type_bet', models.CharField(max_length=11)),
                ('value_bet', models.IntegerField()),
                ('order_of_bet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('final_bettor', models.CharField(max_length=50)),
                ('points_done', models.IntegerField()),
                ('has_won', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ListCards',
            fields=[
                ('card_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value_atout', models.IntegerField()),
                ('value_non_atout', models.IntegerField()),
                ('idc', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_announce', models.CharField(max_length=30)),
                ('total_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamOpponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_east', models.CharField(max_length=100)),
                ('east_hand', models.CharField(max_length=100)),
                ('player_west', models.CharField(max_length=100)),
                ('west_hand', models.CharField(max_length=100)),
                ('east_is_announcing_first', models.IntegerField()),
                ('west_is_announcing_first', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinche.GameLog')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPersonnal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_south', models.CharField(max_length=100)),
                ('south_hand', models.CharField(max_length=100)),
                ('player_north', models.CharField(max_length=100)),
                ('north_hand', models.CharField(max_length=100)),
                ('south_is_announcing_first', models.IntegerField()),
                ('north_is_announcing_first', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinche.GameLog')),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinche.GameLog'),
        ),
    ]
