# Generated by Django 2.1.4 on 2018-12-18 13:44

import coinche.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coinche', '0003_auto_20181217_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_game', models.IntegerField()),
                ('team_personnal', djongo.models.fields.EmbeddedModelField(model_container=coinche.models.TeamPersonnal, null=True)),
                ('team_opponent', djongo.models.fields.EmbeddedModelField(model_container=coinche.models.TeamOpponent, null=True)),
                ('final_bet', djongo.models.fields.EmbeddedModelField(model_container=coinche.models.Bet, null=True)),
                ('final_bettor', models.CharField(max_length=50)),
                ('points_done', models.IntegerField()),
                ('has_won', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_announce', models.CharField(max_length=30)),
                ('total_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamOpponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_east', models.CharField(max_length=100)),
                ('east_hand', models.CharField(max_length=100)),
                ('player_west', models.CharField(max_length=100)),
                ('west_hand', models.CharField(max_length=100)),
                ('east_is_announcing_first', models.IntegerField()),
                ('west_is_announcing_first', models.IntegerField()),
                ('east_bet', djongo.models.fields.EmbeddedModelField(model_container=coinche.models.Bet, null=True)),
                ('west_bet', djongo.models.fields.EmbeddedModelField(model_container=coinche.models.Bet, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPersonnal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_south', models.CharField(max_length=100)),
                ('south_hand', models.CharField(max_length=100)),
                ('player_north', models.CharField(max_length=100)),
                ('north_hand', models.CharField(max_length=100)),
                ('south_is_announcing_first', models.IntegerField()),
                ('north_is_announcing_first', models.IntegerField()),
                ('south_bet', djongo.models.fields.EmbeddedModelField(model_container=coinche.models.Bet, null=True)),
                ('north_bet', djongo.models.fields.EmbeddedModelField(model_container=coinche.models.Bet, null=True)),
            ],
        ),
    ]
