# Generated by Django 2.1.4 on 2018-12-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinche', '0004_gamelog_rules_teamopponent_teampersonnal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamOpponent',
        ),
        migrations.DeleteModel(
            name='TeamPersonnal',
        ),
    ]
