# Generated by Django 2.1.4 on 2018-12-18 21:51

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coinche', '0005_auto_20181218_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('bettor', models.CharField(max_length=11)),
                ('type_bet', models.CharField(max_length=11)),
                ('value_bet', models.IntegerField()),
                ('order_of_bet', models.IntegerField()),
                ('game_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gamelog',
            name='final_bet',
        ),
        migrations.RemoveField(
            model_name='gamelog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gamelog',
            name='id_game',
        ),
        migrations.AddField(
            model_name='gamelog',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
