# Generated by Django 2.1.4 on 2018-12-19 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coinche', '0006_auto_20181218_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamOpponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_east', models.CharField(max_length=100)),
                ('east_hand', models.CharField(max_length=100)),
                ('player_west', models.CharField(max_length=100)),
                ('west_hand', models.CharField(max_length=100)),
                ('east_is_announcing_first', models.IntegerField()),
                ('west_is_announcing_first', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamPersonnal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_south', models.CharField(max_length=100)),
                ('south_hand', models.CharField(max_length=100)),
                ('player_north', models.CharField(max_length=100)),
                ('north_hand', models.CharField(max_length=100)),
                ('south_is_announcing_first', models.IntegerField()),
                ('north_is_announcing_first', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gamelog',
            name='team_opponent',
        ),
        migrations.RemoveField(
            model_name='gamelog',
            name='team_personnal',
        ),
        migrations.AlterField(
            model_name='bet',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinche.GameLog'),
        ),
        migrations.AddField(
            model_name='teampersonnal',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinche.GameLog'),
        ),
        migrations.AddField(
            model_name='teamopponent',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinche.GameLog'),
        ),
    ]
