# Generated by Django 2.1.4 on 2019-01-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinche', '0007_auto_20181219_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcards',
            name='id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
