# Generated by Django 2.1.4 on 2019-01-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinche', '0008_auto_20190107_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcards',
            name='id',
        ),
        migrations.AddField(
            model_name='listcards',
            name='idc',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listcards',
            name='card_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
