# Generated by Django 2.1.7 on 2019-03-21 15:51

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('elo', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('total_played', models.IntegerField()),
                ('total_win', models.IntegerField()),
                ('total_lost', models.IntegerField()),
            ],
        ),
    ]
