# Generated by Django 2.1.4 on 2018-12-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
